import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
 title: 'Mazlum Kaya',
 description: 'Generated by create next app',
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="tr">
   <head>
    <link rel="shortuct icon" href="/favicon.ico" />
   </head>
   <body className={`p-0 m-0 bg-customLight text-customBrown`}>
    <Navbar />
    {children}
    <Footer />
   </body>
  </html>
 );
}
